version: '3.8'

services:
  nodejs: 
    build: .
    ports:
      - '3015:3000'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/flower_order_app
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/flower_order_app