apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-deployment
  namespace: test-ns
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: flower-app
  template:
    metadata:
      labels:
        app: flower-app
    spec:
      containers:
      - name: flower-container
        image: anusocial123/flower-app-image:v1
        ports:
        - containerPort: 3015  
        resources:
            requests:
              memory: "250Mi"
              cpu: "150m"
            limits:
              memory: "500Mi"
              cpu: "250m"
